import { productReviews } from "@/lib/product-data";

type ProductStoryProps = {
  variantId: "mini" | "pro";
};

const storyContent = {
  mini: {
    heading:
      "Mini ball set for soccer fans with a design that celebrates iconic moments.",
    paragraphs: [
      "Be a part of the legacy of global soccer with the FIFA World Cup 26™ Historical Mini Ball Set. From the roar of the crowds to unforgettable plays, this collection is a tribute to the passion, energy, and unity this game brings to fans everywhere. Each mini ball in the set captures the spirit of soccer's most celebrated tournament, echoing decades of competition, hope, and triumph.",
      "Crafted for those who live and breathe the game, from the pros pushing boundaries to fans reliving legendary games, the set is designed to connect you with soccer's rich culture and history. Whether displayed in your home, gifted to a fellow supporter, or added to your collection, this set is a statement of pride and connection.",
      "adidas brings one of the world's biggest soccer stages into your daily life, letting you celebrate iconic moments, legendary teams, and the lasting heritage of the beautiful game with every glance at your set.",
    ],
    details: [
      "Mini replica ball set with display box",
      "Historical World Cup inspired graphics",
      "Foam core construction",
      "No inflation required",
      "Color: White / Multicolor",
      "Product code: JN2093",
    ],
  },
  pro: {
    heading: "A limited-collection boxed set of all 15 adidas World Cup match balls.",
    paragraphs: [
      "Honor the legacy of soccer's most prestigious global event with this FIFA World Cup 26™ Historical Pro Ball Set. A celebration of the long association between adidas and the world-famous competition, it includes a range of instantly recognizable match balls.",
      "From the ball that kicked off the partnership in 1970, the iconic Telstar, to the Trionda, due to star in North America in 2026, you'll find all 15 balls in an eye-catching presentation box.",
      "Each one comes with an adidas Pro ball construction that includes a thermally-bonded, textured surface and a high-grade butyl bladder.",
      "Whether you want to take these classic balls out and use them on the field, or keep them as a memento, this limited-edition set is built to hit the target for fans of the beautiful game’s rich heritage.",
    ],
    details: [
      "61% polyurethane, 30% polyester, 9% rayon",
      "Textured surface",
      "Thermally bonded construction",
      "High-grade butyl bladder",
      "FIFA Quality Pro certification",
      "Product code: KB1812",
    ],
  },
};

export function ProductStory({ variantId }: ProductStoryProps) {
  const content = storyContent[variantId];

  return (
    <>
      <section className="product-story" aria-label="Description and details">
        <div className="story-copy">
          <section className="story-panel">
            <div className="story-panel-header">
              <p className="story-kicker">Description</p>
            </div>
            <h2>{content.heading}</h2>
            {content.paragraphs.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
          </section>

          <section className="details-panel story-panel">
            <div className="story-panel-header">
              <p className="story-kicker">Details</p>
            </div>
            <ul>
              {content.details.map((detail) => (
                <li key={detail}>{detail}</li>
              ))}
            </ul>
          </section>
        </div>
      </section>

      <section className="reviews-section" aria-label="Customer reviews">
        <div className="reviews-header">
          <h2>Reviews</h2>
          <div className="review-header-stars" aria-label="Rating 4.8 out of 5">
            ★★★★★
          </div>
        </div>

        <div className="reviews-summary">
          <div>
            <div className="score-row">
              <strong>4.8</strong>
              <span aria-hidden="true">★★★★★</span>
            </div>
            <h3>Quality</h3>
            <div className="quality-meter" aria-hidden="true">
              <span />
            </div>
            <div className="meter-labels">
              <span>Poor</span>
              <span>Perfect</span>
            </div>
          </div>

        </div>

        <div className="review-ai-summary">
          <h3>What the reviews say</h3>
          <p>
            This summary is generated by artificial intelligence based on
            customer reviews.
          </p>
          <ul>
            <li>
              Customers praise the collection as emotionally resonant, evoking
              cherished memories of past World Cups and personal fandom.
            </li>
            <li>
              Most appreciate the detailed, authentic reproduction of historical
              designs with accurate patterns, textures, and branding.
            </li>
            <li>
              Reviewers highlight the display-ready presentation and individual
              bases for shelves, desks, or display cases.
            </li>
            <li>
              Many value the no-maintenance mini format, making it convenient
              for collectors.
            </li>
          </ul>
        </div>

        <div className="review-list">
          {productReviews.map((review) => (
            <article className="review-card" key={`${review.author}-${review.date}`}>
              <div className="review-author">
                <div className="review-stars" aria-label={`${review.rating} stars`}>
                  {"★".repeat(review.rating)}
                </div>
              </div>

              <div className="review-body">
                <div className="review-title-row">
                  <h3>{review.title}</h3>
                  <time>{review.date}</time>
                </div>
                <p className="review-color">Color: {review.color}</p>
                <p>{review.body}</p>
                <strong className="review-author-name">{review.author}</strong>
                <p className="review-badges">
                  <span className="verified-line">
                    <CheckIcon />
                    Verified Purchaser
                  </span>
                  <span aria-hidden="true">|</span>
                  <span>Incentivized Review</span>
                </p>
                <p className="review-helpful">
                  Helpful?{" "}
                  <span>
                    <LikeIcon /> 0
                  </span>{" "}
                  <span>
                    <DislikeIcon /> 0
                  </span>{" "}
                  <a href="#">Report review</a>
                </p>
              </div>
            </article>
          ))}
        </div>
      </section>
    </>
  );
}

function CheckIcon() {
  return (
    <svg
      width="32"
      height="32"
      viewBox="0 0 32 32"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-hidden="true"
      className="check-icon"
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M26.3536 8.85359L12 23.2071L5.64648 16.8536L6.35359 16.1465L12 21.7929L25.6465 8.14648L26.3536 8.85359Z"
        fill="var(--icon-primary-color, #000)"
      />
    </svg>
  );
}

function LikeIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
    >
      <path
        d="M6.79143 10.254V9.40572H2V16H6.79143V14.7719M6.79143 10.254C6.79143 10.254 7.94834 9.61701 8.5 9C9.15551 8.26684 9.13417 8.27672 9.66629 6.76801C9.96004 5.93512 10.1454 4.1303 10.1454 4.1303C10.1454 4.1303 11.1213 3.83713 11.5829 4.1303C12.0694 4.43932 12.5411 5.84347 12.5411 6.76801C12.5411 7.69254 12.3375 8.52648 12.3375 8.52648H16.8534C18.77 8.9661 17.8117 12.0434 17.3326 13.8019C16.8534 15.5604 14.9369 15.8697 14.9369 15.8697H9L6.79143 14.7719M6.79143 10.254V14.7719"
        stroke="black"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function DislikeIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
    >
      <path
        d="M6.79143 9.74598V10.5943H2V4H6.79143V5.22814M6.79143 9.74598C6.79143 9.74598 7.94834 10.383 8.5 11C9.15551 11.7332 9.13417 11.7233 9.66629 13.232C9.96004 14.0649 10.1454 15.8697 10.1454 15.8697C10.1454 15.8697 11.1213 16.1629 11.5829 15.8697C12.0694 15.5607 12.5411 14.1565 12.5411 13.232C12.5411 12.3075 12.3375 11.4735 12.3375 11.4735H16.8534C18.77 11.0339 17.8117 7.95657 17.3326 6.19809C16.8534 4.43962 14.9369 4.1303 14.9369 4.1303H9L6.79143 5.22814M6.79143 9.74598V5.22814"
        stroke="black"
        strokeLinejoin="round"
      />
    </svg>
  );
}
